### PR TITLE
Fixes for swift 4.2 and xcode 10

### PR DESCRIPTION
**Pull request by romk1n**
- fixes for swift 4.2
- xcode 10

### CODE REVIEW

**Comment by cohen72** [comment]
@glenyi can you merge and update pod? What about Xcode 10.2 / swift 5?

**Comment by bilawal-liaqat** [comment]
@romk1n @cohen72 @glenyi 

How we can use Pod with Swift 4.2 with this update?

**Comment by romk1n** [comment]
@bilawal-liaqat you can reference my repo for it or just create your own and specify it in your cocoa pod file like `pod 'FloatRatingView', :git => 'https://github.com/romk1n/FloatRatingView.git`, :branch => 'fix/xcode10'`

**Comment by bilawal-liaqat** [comment]
@romk1n 
it works.

Thank you

**Pull request merged**
